In [17]:
import pandas as pd
import numpy as np

import talib
from itertools import compress

In [18]:
rawData = pd.read_csv('HistoricalPrices.csv')
rawData.shape

(9327, 5)

In [19]:
rawData

          Date     Open     High      Low    Close
0     12/31/21  4775.21  4786.83  4765.75  4766.18
1     12/30/21  4794.23  4808.93  4775.33  4778.73
2     12/29/21  4788.64  4804.06  4778.08  4793.06
3     12/28/21  4795.49  4807.02  4780.04  4786.35
4     12/27/21  4733.99  4791.49  4733.99  4791.19
...        ...      ...      ...      ...      ...
9322  01/08/85   163.99   164.49   163.99   163.99
9323  01/07/85   164.24   164.62   163.74   164.24
9324  01/04/85   163.68   164.56   163.43   163.68
9325  01/03/85   164.57   166.07   164.44   164.57
9326  01/02/85   165.37   167.12   165.25   165.37

[9327 rows x 5 columns]

In [20]:
rawData = rawData.rename(columns={'Date':'date',' Open': 'open',' High':'high',' Low':'low', ' Close':'close'})

In [21]:
rawData.columns

Index(['date', 'open', 'high', 'low', 'close'], dtype='object')

In [22]:
candle_names = talib.get_function_groups()['Pattern Recognition']

In [23]:
#extract OHLC

# extract OHLC 
op = rawData['open']
hi = rawData['high']
lo = rawData['low']
cl = rawData['close']
# create columns for each pattern
for candle in candle_names:
    # below is same as;
    # rawData["CDL3LINESTRIKE"] = talib.CDL3LINESTRIKE(op, hi, lo, cl)
    rawData[candle] = getattr(talib, candle)(op, hi, lo, cl)

In [24]:
candle_rankings = {
        "CDL3LINESTRIKE_Bull": 1,
        "CDL3LINESTRIKE_Bear": 2,
        "CDL3BLACKCROWS_Bull": 3,
        "CDL3BLACKCROWS_Bear": 3,
        "CDLEVENINGSTAR_Bull": 4,
        "CDLEVENINGSTAR_Bear": 4,
        "CDLTASUKIGAP_Bull": 5,
        "CDLTASUKIGAP_Bear": 5,
        "CDLINVERTEDHAMMER_Bull": 6,
        "CDLINVERTEDHAMMER_Bear": 6,
        "CDLMATCHINGLOW_Bull": 7,
        "CDLMATCHINGLOW_Bear": 7,
        "CDLABANDONEDBABY_Bull": 8,
        "CDLABANDONEDBABY_Bear": 8,
        "CDLBREAKAWAY_Bull": 10,
        "CDLBREAKAWAY_Bear": 10,
        "CDLMORNINGSTAR_Bull": 12,
        "CDLMORNINGSTAR_Bear": 12,
        "CDLPIERCING_Bull": 13,
        "CDLPIERCING_Bear": 13,
        "CDLSTICKSANDWICH_Bull": 14,
        "CDLSTICKSANDWICH_Bear": 14,
        "CDLTHRUSTING_Bull": 15,
        "CDLTHRUSTING_Bear": 15,
        "CDLINNECK_Bull": 17,
        "CDLINNECK_Bear": 17,
        "CDL3INSIDE_Bull": 20,
        "CDL3INSIDE_Bear": 56,
        "CDLHOMINGPIGEON_Bull": 21,
        "CDLHOMINGPIGEON_Bear": 21,
        "CDLDARKCLOUDCOVER_Bull": 22,
        "CDLDARKCLOUDCOVER_Bear": 22,
        "CDLIDENTICAL3CROWS_Bull": 24,
        "CDLIDENTICAL3CROWS_Bear": 24,
        "CDLMORNINGDOJISTAR_Bull": 25,
        "CDLMORNINGDOJISTAR_Bear": 25,
        "CDLXSIDEGAP3METHODS_Bull": 27,
        "CDLXSIDEGAP3METHODS_Bear": 26,
        "CDLTRISTAR_Bull": 28,
        "CDLTRISTAR_Bear": 76,
        "CDLGAPSIDESIDEWHITE_Bull": 46,
        "CDLGAPSIDESIDEWHITE_Bear": 29,
        "CDLEVENINGDOJISTAR_Bull": 30,
        "CDLEVENINGDOJISTAR_Bear": 30,
        "CDL3WHITESOLDIERS_Bull": 32,
        "CDL3WHITESOLDIERS_Bear": 32,
        "CDLONNECK_Bull": 33,
        "CDLONNECK_Bear": 33,
        "CDL3OUTSIDE_Bull": 34,
        "CDL3OUTSIDE_Bear": 39,
        "CDLRICKSHAWMAN_Bull": 35,
        "CDLRICKSHAWMAN_Bear": 35,
        "CDLSEPARATINGLINES_Bull": 36,
        "CDLSEPARATINGLINES_Bear": 40,
        "CDLLONGLEGGEDDOJI_Bull": 37,
        "CDLLONGLEGGEDDOJI_Bear": 37,
        "CDLHARAMI_Bull": 38,
        "CDLHARAMI_Bear": 72,
        "CDLLADDERBOTTOM_Bull": 41,
        "CDLLADDERBOTTOM_Bear": 41,
        "CDLCLOSINGMARUBOZU_Bull": 70,
        "CDLCLOSINGMARUBOZU_Bear": 43,
        "CDLTAKURI_Bull": 47,
        "CDLTAKURI_Bear": 47,
        "CDLDOJISTAR_Bull": 49,
        "CDLDOJISTAR_Bear": 51,
        "CDLHARAMICROSS_Bull": 50,
        "CDLHARAMICROSS_Bear": 80,
        "CDLADVANCEBLOCK_Bull": 54,
        "CDLADVANCEBLOCK_Bear": 54,
        "CDLSHOOTINGSTAR_Bull": 55,
        "CDLSHOOTINGSTAR_Bear": 55,
        "CDLMARUBOZU_Bull": 71,
        "CDLMARUBOZU_Bear": 57,
        "CDLUNIQUE3RIVER_Bull": 60,
        "CDLUNIQUE3RIVER_Bear": 60,
        "CDL2CROWS_Bull": 61,
        "CDL2CROWS_Bear": 61,
        "CDLBELTHOLD_Bull": 62,
        "CDLBELTHOLD_Bear": 63,
        "CDLHAMMER_Bull": 65,
        "CDLHAMMER_Bear": 65,
        "CDLHIGHWAVE_Bull": 67,
        "CDLHIGHWAVE_Bear": 67,
        "CDLSPINNINGTOP_Bull": 69,
        "CDLSPINNINGTOP_Bear": 73,
        "CDLUPSIDEGAP2CROWS_Bull": 74,
        "CDLUPSIDEGAP2CROWS_Bear": 74,
        "CDLGRAVESTONEDOJI_Bull": 77,
        "CDLGRAVESTONEDOJI_Bear": 77,
        "CDLHIKKAKEMOD_Bull": 82,
        "CDLHIKKAKEMOD_Bear": 81,
        "CDLHIKKAKE_Bull": 85,
        "CDLHIKKAKE_Bear": 83,
        "CDLENGULFING_Bull": 84,
        "CDLENGULFING_Bear": 91,
        "CDLMATHOLD_Bull": 86,
        "CDLMATHOLD_Bear": 86,
        "CDLHANGINGMAN_Bull": 87,
        "CDLHANGINGMAN_Bear": 87,
        "CDLRISEFALL3METHODS_Bull": 94,
        "CDLRISEFALL3METHODS_Bear": 89,
        "CDLKICKING_Bull": 96,
        "CDLKICKING_Bear": 102,
        "CDLDRAGONFLYDOJI_Bull": 98,
        "CDLDRAGONFLYDOJI_Bear": 98,
        "CDLCONCEALBABYSWALL_Bull": 101,
        "CDLCONCEALBABYSWALL_Bear": 101,
        "CDL3STARSINSOUTH_Bull": 103,
        "CDL3STARSINSOUTH_Bear": 103,
        "CDLDOJI_Bull": 104,
        "CDLDOJI_Bear": 104
    }

In [25]:
rawData.head()

,date,open,high,low,close,CDL2CROWS,CDL3BLACKCROWS,CDL3INSIDE,CDL3LINESTRIKE,CDL3OUTSIDE,...,CDLSPINNINGTOP,CDLSTALLEDPATTERN,CDLSTICKSANDWICH,CDLTAKURI,CDLTASUKIGAP,CDLTHRUSTING,CDLTRISTAR,CDLUNIQUE3RIVER,CDLUPSIDEGAP2CROWS,CDLXSIDEGAP3METHODS
0,12/31/21,4775.21,4786.83,4765.75,4766.18,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,12/30/21,4794.23,4808.93,4775.33,4778.73,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,12/29/21,4788.64,4804.06,4778.08,4793.06,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,12/28/21,4795.49,4807.02,4780.04,4786.35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,12/27/21,4733.99,4791.49,4733.99,4791.19,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# rawData['candlestick_pattern'] = np.nan
# rawData['candlestick_match_count'] = np.nan
# for index, row in rawData.iterrows():

#     # no pattern found
#     if len(row[candle_names]) - sum(row[candle_names] == 0) == 0:
#         rawData.loc[index,'candlestick_pattern'] = "NO_PATTERN"
#         rawData.loc[index, 'candlestick_match_count'] = 0
#     # single pattern found
#     elif len(row[candle_names]) - sum(row[candle_names] == 0) == 1:
#         # bull pattern 100 or 200
#         if any(row[candle_names].values > 0):
#             pattern = list(compress(row[candle_names].keys(), row[candle_names].values != 0))[0] + '_Bull'
#             rawData.loc[index, 'candlestick_pattern'] = pattern
#             rawData.loc[index, 'candlestick_match_count'] = 1
#         # bear pattern -100 or -200
#         else:
#             pattern = list(compress(row[candle_names].keys(), row[candle_names].values != 0))[0] + '_Bear'
#             rawData.loc[index, 'candlestick_pattern'] = pattern
#             rawData.loc[index, 'candlestick_match_count'] = 1
#     # multiple patterns matched -- select best performance
#     else:
#         # filter out pattern names from bool list of values
#         patterns = list(compress(row[candle_names].keys(), row[candle_names].values != 0))
#         container = []
#         for pattern in patterns:
#             if row[pattern] > 0:
#                 container.append(pattern + '_Bull')
#             else:
#                 container.append(pattern + '_Bear')
#         rank_list = [candle_rankings[p] for p in container]
#         if len(rank_list) == len(container):
#             rank_index_best = rank_list.index(min(rank_list))
#             rawData.loc[index, 'candlestick_pattern'] = container[rank_index_best]
#             rawData.loc[index, 'candlestick_match_count'] = len(container)
# # clean up candle columns
# rawData.drop(candle_names, axis = 1, inplace = True)

In [27]:
import numpy as np
#from candle_rankings import candle_rankings
import talib
from itertools import compress

def recognize_candlestick(df):
    """
    Recognizes candlestick patterns and appends 2 additional columns to df;
    1st - Best Performance candlestick pattern matched by www.thepatternsite.com
    2nd - # of matched patterns
    """

    op = df['open'].astype(float)
    hi = df['high'].astype(float)
    lo = df['low'].astype(float)
    cl = df['close'].astype(float)

    candle_names = talib.get_function_groups()['Pattern Recognition']

    # patterns not found in the patternsite.com
    exclude_items = ('CDLCOUNTERATTACK',
                     'CDLLONGLINE',
                     'CDLSHORTLINE',
                     'CDLSTALLEDPATTERN',
                     'CDLKICKINGBYLENGTH')

    candle_names = [candle for candle in candle_names if candle not in exclude_items]


    # create columns for each candle
    for candle in candle_names:
        # below is same as;
        # df["CDL3LINESTRIKE"] = talib.CDL3LINESTRIKE(op, hi, lo, cl)
        df[candle] = getattr(talib, candle)(op, hi, lo, cl)


    df['candlestick_pattern'] = np.nan
    df['candlestick_match_count'] = np.nan
    for index, row in df.iterrows():

        # no pattern found
        if len(row[candle_names]) - sum(row[candle_names] == 0) == 0:
            df.loc[index,'candlestick_pattern'] = "NO_PATTERN"
            df.loc[index, 'candlestick_match_count'] = 0
        # single pattern found
        elif len(row[candle_names]) - sum(row[candle_names] == 0) == 1:
            # bull pattern 100 or 200
            if any(row[candle_names].values > 0):
                pattern = list(compress(row[candle_names].keys(), row[candle_names].values != 0))[0] + '_Bull'
                df.loc[index, 'candlestick_pattern'] = pattern
                df.loc[index, 'candlestick_match_count'] = 1
            # bear pattern -100 or -200
            else:
                pattern = list(compress(row[candle_names].keys(), row[candle_names].values != 0))[0] + '_Bear'
                df.loc[index, 'candlestick_pattern'] = pattern
                df.loc[index, 'candlestick_match_count'] = 1
        # multiple patterns matched -- select best performance
        else:
            # filter out pattern names from bool list of values
            patterns = list(compress(row[candle_names].keys(), row[candle_names].values != 0))
            container = []
            for pattern in patterns:
                if row[pattern] > 0:
                    container.append(pattern + '_Bull')
                else:
                    container.append(pattern + '_Bear')
            rank_list = [candle_rankings[p] for p in container]
            if len(rank_list) == len(container):
                rank_index_best = rank_list.index(min(rank_list))
                df.loc[index, 'candlestick_pattern'] = container[rank_index_best]
                df.loc[index, 'candlestick_match_count'] = len(container)
    # clean up candle columns
    cols_to_drop = candle_names + list(exclude_items)
    df.drop(cols_to_drop, axis = 1, inplace = True)

    return df

In [28]:
new_data = recognize_candlestick(rawData)

In [30]:
new_data.to_csv('historic_candle_stick.csv',index=False)

In [13]:
df = pd.read_csv('HistoricalPrices.csv')
df.head()

       Date     Open     High      Low    Close
0  12/31/21  4775.21  4786.83  4765.75  4766.18
1  12/30/21  4794.23  4808.93  4775.33  4778.73
2  12/29/21  4788.64  4804.06  4778.08  4793.06
3  12/28/21  4795.49  4807.02  4780.04  4786.35
4  12/27/21  4733.99  4791.49  4733.99  4791.19

In [14]:
from plotly.offline import plot
import plotly.graph_objs as go
import pandas as pd

df = pd.read_csv('HistoricalPrices.csv')

o = df[' Open'].astype(float)
h = df[' High'].astype(float)
l = df[' Low'].astype(float)
c = df[' Close'].astype(float)

trace = go.Candlestick(
            open=o,
            high=h,
            low=l,
            close=c)
data = [trace]

#plot(data, filename='go_candle1.html')


layout = {
    'title': '2019 Feb - 2020 Feb Bitcoin Candlestick Chart',
    'yaxis': {'title': 'Price'},
    'xaxis': {'title': 'Index Number'},

}
fig = dict(data=data, layout=layout)
plot(fig, filename='S&P500 candle stick')

/Users/dannybyers/anaconda3/lib/python3.8/site-packages/plotly/offline/offline.py:562: UserWarning:

Your filename `S&P500 candle stick` didn't end with .html. Adding .html to the end of your file.

'S&P500 candle stick.html'